export const LOADING_CHARACTERS_LIST = "LOADING_CHARACTERS_LIST";
export const SET_CHARACTERS_LIST = "SET_CHARACTERS_LIST";
export const SET_CHARACTER_SELECTED = "SET_CHARACTER_SELECTED";
export const HIDE_MODAL = "HIDE_MODAL";
